name: nft_marketplace CI

on:
  push:
    paths:
      - 'GUI/nft_marketplace/**'
  pull_request:
    paths:
      - 'GUI/nft_marketplace/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm test
      - run: npm run build
