name: mining-staking-manager-ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
        working-directory: GUI/mining-staking-manager
      - run: npm test
        working-directory: GUI/mining-staking-manager
