apiVersion: apps/v1
kind: Deployment
metadata:
  name: mining-staking-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mining-staking-manager
  template:
    metadata:
      labels:
        app: mining-staking-manager
    spec:
      containers:
        - name: mining-staking-manager
          image: mining-staking-manager:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
