site_name: Synnergy Documentation
docs_dir: docs
nav:
  - Home: index.md
  - Guides:
      - Charity: guides/charity_guide.md
      - CLI: guides/cli_guide.md
      - Configuration: guides/config_guide.md
      - Consensus: guides/consensus_guide.md
      - Developer: guides/developer_guide.md
      - LoanPool: guides/loanpool_guide.md
      - Module: guides/module_guide.md
      - Node: guides/node_guide.md
      - Opcode and Gas: guides/opcode_and_gas_guide.md
      - Scripts: guides/script_guide.md
      - Server Setup: guides/server_setup_guide.md
      - Smart Contracts: guides/smart_contract_guide.md
      - Tokens: guides/token_guide.md
      - Transactions: guides/transaction_guide.md
      - Virtual Machine: guides/virtual_machine_guide.md
  - ADRs:
      - "0001 Adopt MkDocs": adr/0001-adopt-mkdocs.md
site_dir: site
