apiVersion: apps/v1
kind: Deployment
metadata:
  name: synnergy-wallet
  labels:
    app: synnergy-wallet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: synnergy-wallet
  template:
    metadata:
      labels:
        app: synnergy-wallet
    spec:
      containers:
      - name: wallet
        image: synnergy/walletserver:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: SYN_CONFIG
          value: /etc/synnergy/config.yaml
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /livez
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /etc/synnergy
      volumes:
      - name: config
        configMap:
          name: syn-wallet-config
---
apiVersion: v1
kind: Service
metadata:
  name: synnergy-wallet
  labels:
    app: synnergy-wallet
spec:
  selector:
    app: synnergy-wallet
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  type: ClusterIP
