version: '3.8'
services:
  explorer:
    build: .
    ports:
      - "3000:3000"
    environment:
      - API_URL=${API_URL:-http://localhost:3000}
      - PORT=3000
    volumes:
      - .:/app
    command: npm start
