blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/example/synnergy/discussions
    about: Use GitHub Discussions for questions and general feedback.
  - name: Security Report
    url: mailto:security@synnergy.example.com
    about: Please disclose vulnerabilities responsibly.
defaults:
  labels:
    - needs-triage
  assignees: []
