blank_issues_enabled: false
defaults:
  labels: []
  assignees: []
contact_links:
  - name: Questions & Discussion
    url: https://github.com/example/synnergy/discussions
    about: Use GitHub Discussions for questions and general feedback.
