apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-operations-center
spec:
  replicas: 2
  selector:
    matchLabels:
      app: security-operations-center
  template:
    metadata:
      labels:
        app: security-operations-center
    spec:
      containers:
        - name: security-operations-center
          image: security-operations-center:latest
          env:
            - name: API_URL
              value: "http://api:8080"
          ports:
            - containerPort: 3000
