version: '3.9'
services:
  synnergy:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: synnergy
    image: synnergy/runtime:stage77
    environment:
      SYN_CONFIG: /configs/dev.yaml
      SYN_RESILIENCE_PROFILE: stage77-ha
      SYN_TELEMETRY_ENDPOINT: http://otel:4318
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8080/livez"]
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - "8080:8080"
      - "30303:30303"
    volumes:
      - ../configs:/configs:ro
      - synnergy-ledger:/var/lib/synnergy
    depends_on:
      otel:
        condition: service_started
    networks:
      - synnergy

  walletserver:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: walletserver
    image: synnergy/wallet:stage77
    environment:
      SYN_CONFIG: /configs/dev-wallet.yaml
      SYN_VIRTUAL_MACHINE_ENDPOINT: http://synnergy:8080
      SYN_WALLET_HSM_CONFIG: /configs/hsm.yaml
    ports:
      - "8090:8081"
    volumes:
      - ../configs:/configs:ro
    depends_on:
      synnergy:
        condition: service_healthy
    networks:
      - synnergy

  otel:
    image: otel/opentelemetry-collector:0.94.0
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ../configs/otel-collector.yaml:/etc/otel-config.yaml:ro
    ports:
      - "4318:4318"
    networks:
      - synnergy

  prometheus:
    image: prom/prometheus:v2.51.0
    volumes:
      - ../configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - synnergy
    depends_on:
      synnergy:
        condition: service_started
      walletserver:
        condition: service_started

  web:
    build:
      context: ../web
    command: npm run start
    environment:
      NEXT_PUBLIC_API_BASE: http://walletserver:8081
    ports:
      - "3000:3000"
    depends_on:
      walletserver:
        condition: service_started
    profiles:
      - ui
    networks:
      - synnergy

volumes:
  synnergy-ledger:

networks:
  synnergy:
    driver: bridge
