apiVersion: apps/v1
kind: Deployment
metadata:
  name: authority-node-index
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authority-node-index
  template:
    metadata:
      labels:
        app: authority-node-index
    spec:
      containers:
        - name: authority-node-index
          image: authority-node-index:latest
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
