apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-management-console
spec:
  replicas: 2
  selector:
    matchLabels:
      app: identity-management-console
  template:
    metadata:
      labels:
        app: identity-management-console
    spec:
      containers:
        - name: identity-management-console
          image: synnergy/identity-management-console:latest
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              value: "https://api.example.com"
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
