apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-admin-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-admin-interface
  template:
    metadata:
      labels:
        app: wallet-admin-interface
    spec:
      containers:
        - name: wallet-admin-interface
          image: wallet-admin-interface:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
