name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Cache modules and build
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Run tests
        run: go test ./...

      - name: Build binaries
        run: |
          mkdir -p dist
          for dir in ./cmd/*; do
            if [ -d "$dir" ]; then
              for os in linux windows darwin; do
                ext=""
                if [ "$os" = "windows" ]; then
                  ext=".exe"
                fi
                GOOS=$os GOARCH=amd64 go build -o dist/$(basename $dir)-$os-amd64$ext $dir
              done
            fi
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: synnergy-binaries
          path: dist
